import Head from 'next/head';
import React from 'react';
import HomePage from '../components/HomePage';

export default function Home() {
    return (
        <div>
            <Head>
                <title>LinkedIn</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-[rgb(206,206,206)]">
                <HomePage />
            </main>
        </div>
    );
}
